name: Build Android APK

on:
  push:
    branches:
      - ci/build-apk
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android build tools and platform
        run: |
          sdkmanager --install "platforms;android-34" "platform-tools" "build-tools;34.0.0"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7

      - name: Prepare web assets for Android
        shell: bash
        run: |
          set -euxo pipefail
          dest="android-app/app/src/main/assets/www"
          mkdir -p "$dest"
          shopt -s nullglob
          # Copy common web assets from repo root (flat structure)
          for f in *.html *.css *.js *.json *.png *.jpg *.jpeg *.svg; do
            cp -a "$f" "$dest/" || true
          done
          # Ensure index.html exists to avoid runtime errors
          test -f "$dest/index.html"

      - name: Build debug APK
        run: |
          gradle -p android-app assembleDebug --no-daemon

      - name: Copy APK to repo path
        run: |
          mkdir -p apk
          cp android-app/app/build/outputs/apk/debug/app-debug.apk apk/quiz-app-debug.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: quiz-app-debug
          path: apk/quiz-app-debug.apk

      - name: Commit and push APK back to branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add apk/quiz-app-debug.apk
          git commit -m "CI: Add built APK [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
